### PR TITLE
Allowing varnishbeat to open the VSM based on a directory parameter.

### PR DESCRIPTION
**Pull request by freshteapot**
varnishbeat -log -c stdout.yml -directory /var/lib/varnish/abc1/

### CODE REVIEW

**Comment by phenomenes** [comment]
Thanks for sending the PR.
I was thinking that rather than passing the vsm directory as a parameter, it could be done in the configuration file.
Would you like to send another PR?

**Comment by freshteapot** [comment]
Great idea!
I will update the request today (tonight)

**Comment by freshteapot** [comment]
Updated (Not sure if you get a note, just because I push code).

**Comment by phenomenes** [comment]
thanks for sending the update. I'll have a look as soon as I find the time.

**Pull request merged**
